import { addDaysISO, toISODate } from '../utils/date';
import type {
  Actor,
  ActorId,
  CaptureEntry,
  CaptureEntryId,
  FlowSession,
  FlowSessionId,
  FocusSession,
  FocusSessionId,
  Intervention,
  InterventionId,
  ISODate,
  ISODateTime,
  Item,
  ItemAssignment,
  ItemAssignmentId,
  ItemId,
  ItemOccurrence,
  ItemOccurrenceId,
  ItemPlan,
  ItemPlanId,
  ItemRelation,
  ItemRelationId,
  LocalTime,
  Ritual,
  RitualId,
  Source,
  SourceId,
  TimeZone,
  TransitionEvent,
  TransitionEventId,
  User,
  UserId,
  Workspace,
  WorkspaceId,
} from '@needle/domain/domain-v2';

const LOCAL_TZ = (Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC') as TimeZone;
const NOW = new Date().toISOString() as ISODateTime;

function isoDateTimeFor(date: ISODate, hhmm: string): ISODateTime {
  return `${date}T${hhmm}:00.000Z` as ISODateTime;
}

export const FIXTURE_TODAY = toISODate() as ISODate;
export const FIXTURE_YESTERDAY = addDaysISO(FIXTURE_TODAY, -1) as ISODate;
export const FIXTURE_TOMORROW = addDaysISO(FIXTURE_TODAY, 1) as ISODate;
export const FIXTURE_IN_THREE_DAYS = addDaysISO(FIXTURE_TODAY, 3) as ISODate;

export const FIXTURE_IDS = {
  workspace: 'ws_personal' as WorkspaceId,
  user: 'user_ofer' as UserId,
  meActor: 'actor_user_ofer' as ActorId,
  sourceManual: 'src_manual' as SourceId,
  sourceCalendar: 'src_calendar' as SourceId,
  flowSession: 'flow_today_ofer' as FlowSessionId,
  focusSession: 'focus_today_ofer' as FocusSessionId,
  transitionStartDay: 'trans_start_day' as TransitionEventId,
  itemOverdueDana: 'item_call_dana' as ItemId,
  itemTodayRecap: 'item_email_recap' as ItemId,
  itemTodayPrep: 'item_prep_1on1' as ItemId,
  itemTodayDeploy: 'item_review_deploy' as ItemId,
  itemTomorrowPr: 'item_review_pr_tal' as ItemId,
  itemUnplannedDentist: 'item_book_dentist' as ItemId,
  itemFutureBirthday: 'item_dad_birthday' as ItemId,
  itemEventStandup: 'item_daily_standup' as ItemId,
  itemEvent1on1: 'item_1on1_manager' as ItemId,
  occStandup: 'occ_standup_today' as ItemOccurrenceId,
  occ1on1: 'occ_1on1_manager_today' as ItemOccurrenceId,
  ritualPreMeeting: 'ritual_pre_1on1' as RitualId,
  interventionCapture: 'int_capture_1on1' as InterventionId,
  interventionTorch: 'int_torch_1on1' as InterventionId,
  interventionEscalation: 'int_escalation_1on1' as InterventionId,
  captureLinked: 'cap_transition_brain' as CaptureEntryId,
} as const;

export type V2FixtureBundle = {
  workspace: Workspace;
  user: User;
  actors: Actor[];
  sources: Source[];
  flowSessions: FlowSession[];
  focusSessions: FocusSession[];
  transitionEvents: TransitionEvent[];
  items: Item[];
  itemRelations: ItemRelation[];
  itemAssignments: ItemAssignment[];
  itemPlans: ItemPlan[];
  itemOccurrences: ItemOccurrence[];
  rituals: Ritual[];
  interventions: Intervention[];
  captureEntries: CaptureEntry[];
  meActorId: ActorId;
};

export function createV2Fixture(): V2FixtureBundle {
  const ids = FIXTURE_IDS;
  const ws = ids.workspace;
  const me = ids.meActor;
  const cal = ids.sourceCalendar;
  const manual = ids.sourceManual;

  const workspace: Workspace = {
    id: ws,
    name: 'Ofer personal',
    kind: 'personal',
    createdByActorId: me,
    createdAt: NOW,
    updatedAt: NOW,
  };

  const user: User = {
    id: ids.user,
    displayName: 'Ofer',
    createdAt: NOW,
    updatedAt: NOW,
  };

  const actors: Actor[] = [
    {
      id: me,
      workspaceId: ws,
      kind: 'user',
      displayName: 'Ofer',
      userId: ids.user,
      metadata: {},
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'actor_ai_companion' as ActorId,
      workspaceId: ws,
      kind: 'ai_agent',
      displayName: 'Needle companion',
      metadata: {},
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'actor_calendar' as ActorId,
      workspaceId: ws,
      kind: 'integration',
      displayName: 'Calendar sync',
      metadata: { provider: 'google' },
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'actor_system' as ActorId,
      workspaceId: ws,
      kind: 'system',
      displayName: 'Needle system',
      metadata: {},
      createdAt: NOW,
      updatedAt: NOW,
    },
  ];

  const sources: Source[] = [
    {
      id: manual,
      workspaceId: ws,
      kind: 'manual',
      label: 'Manual capture',
      metadata: {},
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: cal,
      workspaceId: ws,
      kind: 'calendar',
      label: 'Calendar',
      metadata: {},
      createdAt: NOW,
      updatedAt: NOW,
    },
  ];

  const flowSessions: FlowSession[] = [
    {
      id: ids.flowSession,
      workspaceId: ws,
      actorId: me,
      flowDate: FIXTURE_TODAY,
      state: 'focusing',
      activeItemId: ids.itemTodayPrep,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ];

  const focusSessions: FocusSession[] = [
    {
      id: ids.focusSession,
      workspaceId: ws,
      actorId: me,
      itemId: ids.itemTodayPrep,
      flowSessionId: ids.flowSession,
      startedAt: isoDateTimeFor(FIXTURE_TODAY, '09:00'),
      metadata: {},
      createdAt: NOW,
      updatedAt: NOW,
    },
  ];

  const transitionEvents: TransitionEvent[] = [
    {
      id: ids.transitionStartDay,
      workspaceId: ws,
      actorId: me,
      flowSessionId: ids.flowSession,
      kind: 'start_day',
      prompt: 'What matters most today?',
      createdAt: isoDateTimeFor(FIXTURE_TODAY, '08:30'),
    },
  ];

  const items: Item[] = [
    {
      id: ids.itemOverdueDana,
      workspaceId: ws,
      kind: 'task',
      bucket: 'act',
      title: 'Call back Dana',
      status: 'open',
      visibility: 'workspace',
      commitmentLevel: 'firm',
      sourceId: manual,
      createdByActorId: me,
      updatedByActorId: me,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: ids.itemTodayRecap,
      workspaceId: ws,
      kind: 'task',
      bucket: 'act',
      title: "Email last week's recap",
      status: 'open',
      visibility: 'workspace',
      commitmentLevel: 'soft',
      sourceId: manual,
      createdByActorId: me,
      updatedByActorId: me,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: ids.itemTodayPrep,
      workspaceId: ws,
      kind: 'task',
      bucket: 'act',
      title: 'Prep for manager 1:1',
      status: 'open',
      visibility: 'workspace',
      commitmentLevel: 'firm',
      sourceId: cal,
      createdByActorId: me,
      updatedByActorId: me,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: ids.itemTodayDeploy,
      workspaceId: ws,
      kind: 'task',
      bucket: 'act',
      title: 'Review deployment',
      status: 'open',
      visibility: 'workspace',
      commitmentLevel: 'soft',
      sourceId: manual,
      createdByActorId: me,
      updatedByActorId: me,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: ids.itemTomorrowPr,
      workspaceId: ws,
      kind: 'task',
      bucket: 'act',
      title: 'Review PR from Tal',
      status: 'open',
      visibility: 'workspace',
      commitmentLevel: 'soft',
      sourceId: manual,
      createdByActorId: me,
      updatedByActorId: me,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: ids.itemUnplannedDentist,
      workspaceId: ws,
      kind: 'task',
      bucket: 'act',
      title: 'Book dentist appointment',
      status: 'open',
      visibility: 'workspace',
      commitmentLevel: 'soft',
      sourceId: manual,
      createdByActorId: me,
      updatedByActorId: me,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: ids.itemFutureBirthday,
      workspaceId: ws,
      kind: 'task',
      bucket: 'act',
      title: "Plan dad's birthday gift",
      status: 'open',
      visibility: 'workspace',
      commitmentLevel: 'soft',
      sourceId: manual,
      createdByActorId: me,
      updatedByActorId: me,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'item_sub_prep_notes' as ItemId,
      workspaceId: ws,
      kind: 'task',
      bucket: 'act',
      title: 'Review last 1:1 notes',
      status: 'open',
      visibility: 'workspace',
      commitmentLevel: 'soft',
      sourceId: manual,
      createdByActorId: me,
      updatedByActorId: me,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'item_sub_prep_topics' as ItemId,
      workspaceId: ws,
      kind: 'task',
      bucket: 'act',
      title: 'Pick 2 topics to raise',
      status: 'open',
      visibility: 'workspace',
      commitmentLevel: 'soft',
      sourceId: manual,
      createdByActorId: me,
      updatedByActorId: me,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: ids.itemEventStandup,
      workspaceId: ws,
      kind: 'event',
      bucket: 'act',
      title: 'Daily standup',
      status: 'open',
      visibility: 'workspace',
      commitmentLevel: 'firm',
      sourceId: cal,
      createdByActorId: 'actor_calendar' as ActorId,
      updatedByActorId: 'actor_calendar' as ActorId,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: ids.itemEvent1on1,
      workspaceId: ws,
      kind: 'event',
      bucket: 'act',
      title: 'Manager 1:1',
      status: 'open',
      visibility: 'workspace',
      commitmentLevel: 'unmissable',
      sourceId: cal,
      createdByActorId: 'actor_calendar' as ActorId,
      updatedByActorId: 'actor_calendar' as ActorId,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ];

  const itemOccurrences: ItemOccurrence[] = [
    {
      id: ids.occStandup,
      workspaceId: ws,
      itemId: ids.itemEventStandup,
      startsAt: isoDateTimeFor(FIXTURE_TODAY, '10:30'),
      endsAt: isoDateTimeFor(FIXTURE_TODAY, '10:45'),
      timezone: LOCAL_TZ,
      status: 'confirmed',
      sourceId: cal,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: ids.occ1on1,
      workspaceId: ws,
      itemId: ids.itemEvent1on1,
      startsAt: isoDateTimeFor(FIXTURE_TODAY, '15:00'),
      endsAt: isoDateTimeFor(FIXTURE_TODAY, '15:30'),
      timezone: LOCAL_TZ,
      status: 'confirmed',
      sourceId: cal,
      externalId: 'gcal-evt-abc123',
      createdAt: NOW,
      updatedAt: NOW,
    },
  ];

  const itemPlans: ItemPlan[] = [
    {
      id: 'plan_call_dana' as ItemPlanId,
      workspaceId: ws,
      itemId: ids.itemOverdueDana,
      actorId: me,
      planDate: FIXTURE_YESTERDAY,
      mode: 'float',
      timezone: LOCAL_TZ,
      slotIndex: 0,
      slotOrder: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'plan_email_recap' as ItemPlanId,
      workspaceId: ws,
      itemId: ids.itemTodayRecap,
      actorId: me,
      planDate: FIXTURE_TODAY,
      mode: 'float',
      timezone: LOCAL_TZ,
      slotIndex: 0,
      slotOrder: 100,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'plan_prep_1on1' as ItemPlanId,
      workspaceId: ws,
      itemId: ids.itemTodayPrep,
      actorId: me,
      planDate: FIXTURE_TODAY,
      mode: 'float',
      timezone: LOCAL_TZ,
      relativeTo: { occurrenceId: ids.occ1on1, offsetMinutes: -120 },
      slotIndex: 1,
      slotOrder: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'plan_review_deploy' as ItemPlanId,
      workspaceId: ws,
      itemId: ids.itemTodayDeploy,
      actorId: me,
      planDate: FIXTURE_TODAY,
      mode: 'float',
      timezone: LOCAL_TZ,
      slotIndex: 2,
      slotOrder: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'plan_review_pr' as ItemPlanId,
      workspaceId: ws,
      itemId: ids.itemTomorrowPr,
      actorId: me,
      planDate: FIXTURE_TOMORROW,
      mode: 'float',
      timezone: LOCAL_TZ,
      slotIndex: 0,
      slotOrder: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'plan_dentist' as ItemPlanId,
      workspaceId: ws,
      itemId: ids.itemUnplannedDentist,
      actorId: me,
      mode: 'stash',
      timezone: LOCAL_TZ,
      slotIndex: 0,
      slotOrder: 100,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'plan_birthday' as ItemPlanId,
      workspaceId: ws,
      itemId: ids.itemFutureBirthday,
      actorId: me,
      planDate: FIXTURE_IN_THREE_DAYS,
      mode: 'float',
      timezone: LOCAL_TZ,
      slotIndex: 0,
      slotOrder: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'plan_event_standup' as ItemPlanId,
      workspaceId: ws,
      itemId: ids.itemEventStandup,
      actorId: me,
      planDate: FIXTURE_TODAY,
      mode: 'anchor',
      startTime: '10:30' as LocalTime,
      endTime: '10:45' as LocalTime,
      timezone: LOCAL_TZ,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'plan_event_1on1' as ItemPlanId,
      workspaceId: ws,
      itemId: ids.itemEvent1on1,
      actorId: me,
      planDate: FIXTURE_TODAY,
      mode: 'anchor',
      startTime: '15:00' as LocalTime,
      endTime: '15:30' as LocalTime,
      timezone: LOCAL_TZ,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ];

  const itemRelations: ItemRelation[] = [
    {
      id: 'rel_prep_for_1on1' as ItemRelationId,
      workspaceId: ws,
      fromItemId: ids.itemTodayPrep,
      toItemId: ids.itemEvent1on1,
      relationType: 'prep_for',
      sortOrder: 0,
      createdByActorId: me,
      createdAt: NOW,
    },
    {
      id: 'rel_contains_prep_notes' as ItemRelationId,
      workspaceId: ws,
      fromItemId: ids.itemTodayPrep,
      toItemId: 'item_sub_prep_notes' as ItemId,
      relationType: 'contains',
      sortOrder: 0,
      createdByActorId: me,
      createdAt: NOW,
    },
    {
      id: 'rel_contains_prep_topics' as ItemRelationId,
      workspaceId: ws,
      fromItemId: ids.itemTodayPrep,
      toItemId: 'item_sub_prep_topics' as ItemId,
      relationType: 'contains',
      sortOrder: 1,
      createdByActorId: me,
      createdAt: NOW,
    },
  ];

  const itemAssignments: ItemAssignment[] = [
    {
      id: 'assign_ofer_prep' as ItemAssignmentId,
      workspaceId: ws,
      itemId: ids.itemTodayPrep,
      actorId: me,
      role: 'owner',
      status: 'open',
      createdByActorId: me,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ];

  const rituals: Ritual[] = [
    {
      id: ids.ritualPreMeeting,
      workspaceId: ws,
      actorId: me,
      createdByActorId: me,
      kind: 'pre_meeting_capture',
      name: '5-min brain-dump before unmissable meetings',
      trigger: {
        kind: 'before_occurrence',
        offsetMinutes: -5,
        match: { itemKinds: ['event'], minCommitmentLevel: 'unmissable' },
      },
      actions: [
        { kind: 'open_capture' },
        {
          kind: 'fire_intervention',
          strategy: 'modal_capture',
          surface: 'in_app',
          intensity: 2,
        },
        {
          kind: 'fire_intervention',
          strategy: 'attention_takeover_torch',
          surface: 'screen_overlay',
          intensity: 4,
          offsetMinutes: -1,
        },
      ],
      enabled: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ];

  const interventions: Intervention[] = [
    {
      id: ids.interventionCapture,
      workspaceId: ws,
      actorId: me,
      createdByActorId: 'actor_system' as ActorId,
      strategy: 'modal_capture',
      surface: 'in_app',
      intensity: 2,
      triggeredBy: 'ritual',
      itemId: ids.itemTodayPrep,
      occurrenceId: ids.occ1on1,
      flowSessionId: ids.flowSession,
      ritualId: ids.ritualPreMeeting,
      scheduledFor: isoDateTimeFor(FIXTURE_TODAY, '14:55'),
      status: 'scheduled',
      payload: { title: 'Brain-dump before Manager 1:1', subtitle: 'Anything on your mind?' },
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: ids.interventionTorch,
      workspaceId: ws,
      actorId: me,
      createdByActorId: 'actor_system' as ActorId,
      strategy: 'attention_takeover_torch',
      surface: 'screen_overlay',
      intensity: 4,
      triggeredBy: 'ritual',
      itemId: ids.itemEvent1on1,
      occurrenceId: ids.occ1on1,
      flowSessionId: ids.flowSession,
      ritualId: ids.ritualPreMeeting,
      scheduledFor: isoDateTimeFor(FIXTURE_TODAY, '14:59'),
      status: 'scheduled',
      escalatesToInterventionId: ids.interventionEscalation,
      payload: {
        title: 'Manager 1:1 starting',
        subtitle: 'Move to it now.',
        targetItemId: ids.itemEvent1on1,
      },
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: ids.interventionEscalation,
      workspaceId: ws,
      actorId: me,
      createdByActorId: 'actor_system' as ActorId,
      strategy: 'escalated_alert',
      surface: 'in_app',
      intensity: 5,
      triggeredBy: 'escalation',
      itemId: ids.itemEvent1on1,
      occurrenceId: ids.occ1on1,
      flowSessionId: ids.flowSession,
      ritualId: ids.ritualPreMeeting,
      scheduledFor: isoDateTimeFor(FIXTURE_TODAY, '15:00'),
      status: 'scheduled',
      payload: { title: 'Manager 1:1 is happening now', subtitle: 'You missed the heads-up.' },
      createdAt: NOW,
      updatedAt: NOW,
    },
  ];

  const captureEntries: CaptureEntry[] = [
    {
      id: ids.captureLinked,
      workspaceId: ws,
      actorId: me,
      body: 'Remember to ask Maya about the hiring plan',
      status: 'raw',
      transitionEventId: ids.transitionStartDay,
      flowSessionId: ids.flowSession,
      capturedAt: isoDateTimeFor(FIXTURE_TODAY, '08:35'),
      createdAt: NOW,
      updatedAt: NOW,
    },
  ];

  return {
    workspace,
    user,
    actors,
    sources,
    flowSessions,
    focusSessions,
    transitionEvents,
    items,
    itemRelations,
    itemAssignments,
    itemPlans,
    itemOccurrences,
    rituals,
    interventions,
    captureEntries,
    meActorId: me,
  };
}
